[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
autoImportCompletions = true

[[language]]
name = "python"
language-servers = ["pyright", "ruff"]
formatter = { command = "black", args = ["--line-length", "120", "--quiet", "-"] }
auto-format = true
roots = ["pyproject.toml", "setup.py", "setup.cfg", ".git"]

[[language]]
name = "hcl"
formatter = { command = "terraform", args = ["fmt"] }
auto-format = true
